## Problem Statement

The IPL is a fast-paced T20 league, and understanding match trends can be complex. This project analyzes **ball-by-ball data (2008-2023)** to explore **batting, bowling, match results, and venue impact** using **Exploratory Data Analysis (EDA)** to uncover key insights.

## **Dataset Info:**

**Match ID** : Unique identifier for each match.

**Date**: Date on which the match was played.

**Venue** : Name of the stadium where the match was played.

**Bat First** : Name of the team that batted first.

**Bat Second** : Name of the team that batted second.

**Innings** : Indicates the inning number (1 or 2) of the match.

**Over** : Specifies the over number within the inning.

**Ball** : Denotes the ball number within the over.

**Batter** : Name of the batsman facing the delivery.

**Non Striker** : Name of the non-striking batsman.

**Bowler** : Name of the bowler delivering the ball.

**Batter Runs** : Runs scored by the batsman on that specific delivery.

**Extra Runs** : Additional runs awarded due to extras like wides or no-balls.

**Runs From Ball** : Total runs scored from that delivery (batsman + extras).

**Ball Rebowled** : Indicator if the ball was rebowled (e.g., after a no-ball).

**Extra Type** : Type of extra run conceded (e.g., wide, no-ball, leg bye, bye).

**Wicket** : Indicates if a wicket fell on that delivery (1 for yes, 0 for no).

**Method** : Type of dismissal (e.g., bowled, caught, run out, etc.).

**Player Out** : Name of the dismissed player, if applicable.

**Innings Runs** : Total runs scored in the inning up to that ball.

**Innings Wickets** : Total number of wickets lost in the inning up to that ball.

**Target Score** : The target score set by the batting team (useful in chases).

**Runs to Get** : Runs required to win the match (only in chases).

**Balls Remaining** : Number of balls left in the innings.

**Winner** : Name of the team that won the match.

**Chased Successfully** : Indicator if the target was successfully chased (1 for yes, 0 for no).

**Total Batter Runs** : The total runs accumulated by the batter up until this delivery in the innings

**Total Non Striker Runs** : The total runs accumulated by the non-striker up until this delivery in the innings

**Batter Balls Faced** : The number of valid deliveries faced by the batter up until this delivery in the innings.

**Non Striker Balls Faced** : The number of valid deliveries faced by the non-striker up until this delivery in the innings.

**Player Out Runs** : The total runs scored by the dismissed player before getting out

**Player Out Balls Faced** : The number of valid deliveries faced by the dismissed player before getting out

**Bowler Runs Conceded** : Total runs conceded by the bowler in that ball.

**Valid Ball** : Indicates if the delivery was a valid ball (not wide/no-ball).

## **Import Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

## **Load Data**

In [ ]:
df = pd.read_csv('/content/ball_by_ball_ipl.csv', index_col = 0)

### **Dataset Overview & Structure**

In [ ]:
df.head()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,1,0,NaN,NaN,4,1
1,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,2,0,NaN,NaN,0,1
2,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,3,0,NaN,NaN,0,1
3,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,4,0,NaN,NaN,0,1
4,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,5,0,5,0,NaN,NaN,1,1

In [ ]:
df.tail()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
239688,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,1,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,16,31,9,29,NaN,NaN,2,1
239689,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,2,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,22,31,10,29,NaN,NaN,6,1
239690,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,3,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,26,31,11,29,NaN,NaN,4,1
239691,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,4,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,27,31,12,29,NaN,NaN,1,1
239692,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,5,KS Williamson,YK Pathan,...,Sunrisers Hyderabad,1,32,27,30,12,NaN,NaN,1,1

In [ ]:
df.shape

(239693, 34)

#### **Identifying key columns and understanding data types**

In [ ]:
df.columns

Index(['Match ID', 'Date', 'Venue', 'Bat First', 'Bat Second', 'Innings',
       'Over', 'Ball', 'Batter', 'Non Striker', 'Bowler', 'Batter Runs',
       'Extra Runs', 'Runs From Ball', 'Ball Rebowled', 'Extra Type', 'Wicket',
       'Method', 'Player Out', 'Innings Runs', 'Innings Wickets',
       'Target Score', 'Runs to Get', 'Balls Remaining', 'Winner',
       'Chased Successfully', 'Total Batter Runs', 'Total Non Striker Runs',
       'Batter Balls Faced', 'Non Striker Balls Faced', 'Player Out Runs',
       'Player Out Balls Faced', 'Bowler Runs Conceded', 'Valid Ball'],
      dtype='object')

In [ ]:
df.dtypes

Match ID                     int64
Date                        object
Venue                       object
Bat First                   object
Bat Second                  object
Innings                      int64
Over                         int64
Ball                         int64
Batter                      object
Non Striker                 object
Bowler                      object
Batter Runs                  int64
Extra Runs                   int64
Runs From Ball               int64
Ball Rebowled                int64
Extra Type                  object
Wicket                       int64
Method                      object
Player Out                  object
Innings Runs                 int64
Innings Wickets              int64
Target Score                 int64
Runs to Get                float64
Balls Remaining              int64
Winner                      object
Chased Successfully          int64
Total Batter Runs            int64
Total Non Striker Runs       int64
Batter Balls Faced           int64
Non Striker Balls Faced      int64
Player Out Runs            float64
Player Out Balls Faced     float64
Bowler Runs Conceded         int64
Valid Ball                   int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 239693 entries, 0 to 239692
Data columns (total 34 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Match ID                 239693 non-null  int64
 1   Date                     239693 non-null  object
 2   Venue                    239693 non-null  object
 3   Bat First                239693 non-null  object
 4   Bat Second               239693 non-null  object
 5   Innings                  239693 non-null  int64
 6   Over                     239693 non-null  int64
 7   Ball                     239693 non-null  int64
 8   Batter                   239693 non-null  object
 9   Non Striker              239693 non-null  object
 10  Bowler                   239693 non-null  object
 11  Batter Runs              239693 non-null  int64
 12  Extra Runs               239693 non-null  int64
 13  Runs From Ball           239693 non-null  int64
 14  Ball Rebowled            239693 non-null  int64
 15  Extra Type               239693 non-null  object
 16  Wicket                   239693 non-null  int64
 17  Method                   11827 non-null   object
 18  Player Out               11827 non-null   object
 19  Innings Runs             239693 non-null  int64
 20  Innings Wickets          239693 non-null  int64
 21  Target Score             239693 non-null  int64
 22  Runs to Get              115766 non-null  float64
 23  Balls Remaining          239693 non-null  int64
 24  Winner                   239693 non-null  object
 25  Chased Successfully      239693 non-null  int64
 26  Total Batter Runs        239693 non-null  int64
 27  Total Non Striker Runs   239693 non-null  int64
 28  Batter Balls Faced       239693 non-null  int64
 29  Non Striker Balls Faced  239693 non-null  int64
 30  Player Out Runs          11827 non-null   float64
 31  Player Out Balls Faced   11827 non-null   float64
 32  Bowler Runs Conceded     239693 non-null  int64
 33  Valid Ball               239693 non-null  int64
dtypes: float64(3), int64(20), object(11)
memory usage: 64.0+ MB

## **Data Cleaning**

###**Standardizing Categorical Data**

Before moving to analysis, ensure data consistency in categorical values:
Checking key categorical columns prevents errors in grouping, filtering, and aggregations

In [ ]:
categorical_columns = df.select_dtypes(include= ['object', 'category']).columns.tolist()
print(categorical_columns)

['Date', 'Venue', 'Bat First', 'Bat Second', 'Batter', 'Non Striker', 'Bowler', 'Extra Type', 'Method', 'Player Out', 'Winner']

#### **Cleaning Venue Names**

In [ ]:
df['Venue'].unique()

array(['Eden Gardens', 'De Beers Diamond Oval', 'Sharjah Cricket Stadium',
       'Wankhede Stadium', 'Feroz Shah Kotla', 'Holkar Cricket Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Maharashtra Cricket Association Stadium',
       'MA Chidambaram Stadium', 'Dubai International Cricket Stadium',
       'Kingsmead', 'Dr DY Patil Sports Academy', 'SuperSport Park',
       'Sawai Mansingh Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'M Chinnaswamy Stadium', 'Rajiv Gandhi International Stadium',
       'Brabourne Stadium', 'Sheikh Zayed Stadium',
       'M.Chinnaswamy Stadium', 'Punjab Cricket Association Stadium',
       'Narendra Modi Stadium', 'Arun Jaitley Stadium',
       'Barabati Stadium', 'Saurashtra Cricket Association Stadium',
       'Sardar Patel Stadium',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Green Park', 'Subrata Roy Sahara Stadium',
       'JSCA International Stadium Complex',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Zayed Cricket Stadium', 'Vidarbha Cricket Association Stadium',
       "St George's Park",
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
       'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval',
       'Buffalo Park', 'Barsapara Cricket Stadium'], dtype=object)

In [ ]:
# Standardizing Venue Names
venue_map = {
    "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",
    "Sardar Patel Stadium": "Narendra Modi Stadium",
    "Punjab Cricket Association IS Bindra Stadium": "Punjab Cricket Association Stadium",
    "Feroz Shah Kotla": "Arun Jaitley Stadium",
    "Zayed Cricket Stadium": "Sheikh Zayed Stadium",
    "De Beers Diamond Oval": "Kimberley Oval",
    "Rajiv Gandhi International Stadium": "Uppal Stadium",
    "Dr Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "ACA-VDCA Stadium",
    "Shaheed Veer Narayan Singh International Stadium": "Raipur International Cricket Stadium",
    "JSCA International Stadium Complex": "Ranchi Stadium",
    "Barsapara Cricket Stadium": "Assam Cricket Association Stadium"
}

df['Venue'] = df['Venue'].replace(venue_map)

IPL teams wikipedia : https://en.wikipedia.org/wiki/Indian_Premier_League#:~:text=Timeline%20of%20teams

####**Cleaning Team Names**

In [ ]:
df['Bat First'].unique()

array(['Chennai Super Kings', 'Rajasthan Royals', 'Mumbai Indians',
       'Delhi Daredevils', 'Royal Challengers Bangalore',
       'Delhi Capitals', 'Sunrisers Hyderabad', 'Rising Pune Supergiants',
       'Punjab Kings', 'Kings XI Punjab', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Deccan Chargers', 'Kolkata Knight Riders',
       'Gujarat Titans', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Lucknow Super Giants'], dtype=object)

In [ ]:
df['Bat Second'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Delhi Capitals',
       'Kings XI Punjab', 'Kochi Tuskers Kerala', 'Delhi Daredevils',
       'Mumbai Indians', 'Gujarat Titans', 'Rajasthan Royals',
       'Royal Challengers Bangalore', 'Deccan Chargers',
       'Sunrisers Hyderabad', 'Lucknow Super Giants', 'Punjab Kings',
       'Pune Warriors', 'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant'], dtype=object)

In [ ]:
df['Winner'].unique()

array(['Chennai Super Kings', 'Delhi Capitals', 'Mumbai Indians',
       'Kings XI Punjab', 'Kochi Tuskers Kerala',
       'Royal Challengers Bangalore', 'Gujarat Titans', 'Punjab Kings',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Pune Warriors',
       'Rajasthan Royals', 'Sunrisers Hyderabad', 'Lucknow Super Giants',
       'Deccan Chargers', 'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant'], dtype=object)

In [ ]:
team_name_map = {
    "Delhi Daredevils": "Delhi Capitals",
    "Kings XI Punjab": "Punjab Kings"
}
df["Bat First"] = df["Bat First"].replace(team_name_map)
df["Bat Second"] = df["Bat Second"].replace(team_name_map)
df["Winner"] = df["Winner"].replace(team_name_map)

In [ ]:
df['Bat First'].unique()

array(['Chennai Super Kings', 'Rajasthan Royals', 'Mumbai Indians',
       'Delhi Capitals', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad', 'Rising Pune Supergiants', 'Punjab Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Deccan Chargers',
       'Kolkata Knight Riders', 'Gujarat Titans',
       'Rising Pune Supergiant', 'Gujarat Lions', 'Lucknow Super Giants'],
      dtype=object)

#### **Cleaning Player Names**

In [ ]:
# Standardizing Player Names
df["Batter"] = df["Batter"].str.strip().str.title()
df["Non Striker"] = df["Non Striker"].str.strip().str.title()
df["Bowler"] = df["Bowler"].str.strip().str.title()
df["Player Out"] = df["Player Out"].str.strip().str.title()

### **Handling Missing & Duplicated Data**

#### **Identifying Missing values**

In [ ]:
df.isna().sum()

Match ID                        0
Date                            0
Venue                           0
Bat First                       0
Bat Second                      0
Innings                         0
Over                            0
Ball                            0
Batter                          0
Non Striker                     0
Bowler                          0
Batter Runs                     0
Extra Runs                      0
Runs From Ball                  0
Ball Rebowled                   0
Extra Type                      0
Wicket                          0
Method                     227866
Player Out                 227866
Innings Runs                    0
Innings Wickets                 0
Target Score                    0
Runs to Get                123927
Balls Remaining                 0
Winner                          0
Chased Successfully             0
Total Batter Runs               0
Total Non Striker Runs          0
Batter Balls Faced              0
Non Striker Balls Faced         0
Player Out Runs            227866
Player Out Balls Faced     227866
Bowler Runs Conceded            0
Valid Ball                      0
dtype: int64



#### Observations:

* **Method** has **227,866 missing values** because it is only applicable when a wicket falls. It is **NaN for deliveries where no wicket fell**.  
* **Player Out** has **227,866 missing values** as it is recorded only when a wicket falls, making it **NaN for non-wicket deliveries**.  
* **Player Out Runs** has **227,866 missing values** because it is missing for deliveries where no player was out.  
* **Player Out Balls Faced** has **227,866 missing values** for the same reason—it is recorded only when a player gets out.  
* **Runs to Get** has **123,927 missing values** as it is **only relevant for the second innings**, making it **NaN for the first innings**.

In [ ]:
df.dropna()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
126,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,1,4,Sp Narine,N Jagadeesan,...,Chennai Super Kings,0,0,1,0,1,0.0,3.0,0,1
130,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,2,2,N Jagadeesan,Vr Iyer,...,Chennai Super Kings,0,0,0,0,2,1.0,3.0,0,1
167,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,8,1,Vr Iyer,N Rana,...,Chennai Super Kings,0,0,22,0,18,20.0,20.0,0,1
174,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,9,2,N Rana,Jj Roy,...,Chennai Super Kings,0,0,19,0,4,27.0,21.0,0,1
213,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,15,3,Jj Roy,Rk Singh,...,Chennai Super Kings,0,0,21,0,16,61.0,27.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239434,598012,2013-04-13,MA Chidambaram Stadium,Royal Challengers Bangalore,Chennai Super Kings,2,19,1,Ms Dhoni,Ra Jadeja,...,Chennai Super Kings,1,0,26,0,16,33.0,24.0,0,1
239438,598012,2013-04-13,MA Chidambaram Stadium,Royal Challengers Bangalore,Chennai Super Kings,2,19,4,Dj Bravo,Ra Jadeja,...,Chennai Super Kings,1,0,26,0,16,8.0,4.0,0,1
239624,1136596,2018-05-05,Uppal Stadium,Delhi Capitals,Sunrisers Hyderabad,2,9,6,Ad Hales,S Dhawan,...,Sunrisers Hyderabad,1,0,28,0,24,45.0,31.0,0,1
239637,1136596,2018-05-05,Uppal Stadium,Delhi Capitals,Sunrisers Hyderabad,2,11,6,S Dhawan,Ks Williamson,...,Sunrisers Hyderabad,1,0,4,0,6,33.0,31.0,0,1
239675,1136596,2018-05-05,Uppal Stadium,Delhi Capitals,Sunrisers Hyderabad,2,18,1,Mk Pandey,Ks Williamson,...,Sunrisers Hyderabad,1,0,28,0,26,21.0,18.0,0,1

In [ ]:
# replacing missing values

df['Method'].fillna('Not Out', inplace=True)

df['Player Out'].fillna('None', inplace=True)
df['Player Out Runs'].fillna(0, inplace=True)

df['Player Out Balls Faced'].fillna(0, inplace=True)
df['Runs to Get'].fillna(0, inplace=True)

In [ ]:
df.isnull().sum()

Match ID                   0
Date                       0
Venue                      0
Bat First                  0
Bat Second                 0
Innings                    0
Over                       0
Ball                       0
Batter                     0
Non Striker                0
Bowler                     0
Batter Runs                0
Extra Runs                 0
Runs From Ball             0
Ball Rebowled              0
Extra Type                 0
Wicket                     0
Method                     0
Player Out                 0
Innings Runs               0
Innings Wickets            0
Target Score               0
Runs to Get                0
Balls Remaining            0
Winner                     0
Chased Successfully        0
Total Batter Runs          0
Total Non Striker Runs     0
Batter Balls Faced         0
Non Striker Balls Faced    0
Player Out Runs            0
Player Out Balls Faced     0
Bowler Runs Conceded       0
Valid Ball                 0
dtype: int64

Check for Duplicates

In [ ]:
df.duplicated().sum()

np.int64(0)

No Duplicates found

###**Data Type Corrections**

**Match ID** should be converted from **int64** to **str** because it represents a categorical value, not a numerical one.

**Date** should be converted from **object** to **datetime64** since it is needed for time-series analysis.

**Ball Reboweled** should be converted from **int64** to **bool** by mapping 1 → True and 0 → False.

**Runs to Get** should be converted from **float64** to **int64** because runs are always whole numbers.

**Player Out Runs** should be converted from **object** to **int64** because it should be a numeric column.

**Player Out Balls** Faced should be converted from **float64** to **int64** because it should be an integer.

In [ ]:
# Convert Match ID to string
df['Match ID'] = df['Match ID'].astype(str)

# Convert Date to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Convert Ball Rebowled to boolean
df['Ball Rebowled'] = df['Ball Rebowled'].astype(bool)

# Convert Runs to Get to integer
df['Runs to Get'] = df['Runs to Get'].astype(int)

# Convert Player Out Runs to integer
df['Player Out Runs'] = df['Player Out Runs'].astype(int)

# Convert Player Out Balls Faced to integer
df['Player Out Balls Faced'] = df['Player Out Balls Faced'].astype(int)